"""add feedback likes and comments

Revision ID: fe901fef0de9
Revises: 77e8e5e3a94d
Create Date: 2026-09-06 19:20:14.777021

"""
from alembic import op
import sqlalchemy as sa


revision = 'fe901fef0de9'
down_revision = '77e8e5e3a94d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['feedback_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_comments_post_id'), 'feedback_comments', ['post_id'], unique=False)
    op.create_table('feedback_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feedback_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_feedback_like')
    )
    op.create_index(op.f('ix_feedback_likes_post_id'), 'feedback_likes', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_likes_post_id'), table_name='feedback_likes')
    op.drop_table('feedback_likes')
    op.drop_index(op.f('ix_feedback_comments_post_id'), table_name='feedback_comments')
    op.drop_table('feedback_comments')
    # ### end Alembic commands ###
